- name: Update instances
  hosts: tag_Name_Test_Drupal
  gather_facts: True
  user: ubuntu
  sudo: yes
  vars:
    db_name: drupal
    db_user: drupal_user
    db_password: password1
  tasks:
    - name: Create Drupal Database User
      mysql_user: name={{ db_user }} password={{ db_password }} priv={{ db_name }}.*:ALL
        
    - name: Installing Git
      apt: name=git state=latest

    - name: Installing Drush
      apt: name=drush state=latest
      
    - name: Creating directory for Drupal installation
      file: path=/var/www/html/drupal state=directory

    - name: Install Drupal 8
      command: drush dl drupal-8
