- name: Update instances
  hosts: tag_Name_Test_Drupal
  gather_facts: True
  user: ubuntu
  sudo: yes
  vars:
    db_name: drupal
    db_user: drupal_user
    db_password: password1
  tasks:
    - name: Move files to drupal directory
      command: mv /home/ubuntu/drupal-8.0.6 /var/www/html/drupal/

    - name: Delete temp directory after moving files
      command: rm -rf drupal-8.0.6/

    - name: "Create settings.php"
      command: cp /var/www/html/drupal/sites/default/default.settings.php /var/www/html/drupal/sites/default/settings.php

    - name: "Create services.yml"
      command: cp /var/www/html/drupal/sites/default/default.services.yml /var/www/html/drupal/sites/default/services.yml

    - name: Make files subdirectory
      file: path=/var/www/html/drupal/sites/default/files state=directory

    - name: Change file permissions
      command: chmod a+w /var/www/html/drupal/sites/default

    - name: Change file group permissions
      command: chown -R www-data:www-data /var/www/html/drupal/
