---

- name: Install PHP and associated packages
  apt: name=php5 state=latest

- name: Install PHP GD library
  apt: name=php5-gd state=latest

- name: Restart Apache
  service: name=apache2 state=restarted
